# docker-compose.yml
version: '3.1'
services:
  backend:
    image: scheduler_backend:latest
    container_name: scheduler_backend
    ports:
      - "8080:8080"
  postgres:
    image: postgres:14.2-alpine
    container_name: scheduler_db
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: scheduler_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
  frontend:
    image: scheduler_frontend:latest
    container_name: scheduler_frontend
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/static:/usr/src/app/static
